import type { WorkflowFailureEvent, WorkflowSourceSummary } from "@awm/shared";

const N8N_BASE = "https://awm.app.n8n.cloud";
const ZAP_HISTORY = "https://zapier.com/app/history";

/** Minutes → ISO string relative to now, so fixture data always looks live. */
function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export const WORKFLOW_SOURCES_FIXTURE: WorkflowSourceSummary[] = [
  { id: "src-n8n", name: "AWM n8n", platform: "n8n", sweepEnabled: true },
  { id: "src-zapier", name: "AWM Zapier", platform: "zapier", sweepEnabled: false },
  { id: "src-taskbooker", name: "Task Booker Jobs", platform: "custom_app", sweepEnabled: false },
];

export function buildWorkflowEventsFixture(): WorkflowFailureEvent[] {
  return [
    {
      id: "evt-001",
      platform: "n8n",
      eventType: "execution_failed",
      status: "new",
      sourceName: "AWM n8n",
      workflowExternalId: "wf-insightly-sync",
      workflowName: "Insightly → Supabase Contact Sync",
      executionExternalId: "84213",
      executionUrl: `${N8N_BASE}/workflow/wf-insightly-sync/executions/84213`,
      errorMessage: "429 Too Many Requests — Insightly rate limit exceeded (10 req/s)",
      errorNode: "Insightly: Update Contact",
      errorStack:
        "NodeApiError: 429 Too Many Requests\n    at Object.execute (n8n-nodes-base/Insightly/Insightly.node.ts:214)\n    at Workflow.runNode (n8n-workflow/src/Workflow.ts:1301)",
      occurredAt: ago(12),
      receivedAt: ago(12),
      ingestChannel: "push",
      assignee: null,
      acknowledgedAt: null,
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: true,
      inputPayload: {
        batch: { contactIds: ["INS-88121", "INS-88134", "INS-88139"], updatedSince: "2026-08-25T08:00:00Z" },
      },
      canResubmit: false,
      fixSuggestion: {
        summary: "Batch the Insightly updates and retry on rate-limit",
        changes: [
          "Insert a 'Loop Over Items' node (batch size 5) with a 1s Wait between batches before 'Insightly: Update Contact'",
          "Enable 'Retry On Fail' on the node: 3 tries, 2s wait — absorbs transient 429s",
        ],
        mechanism:
          "Applies via n8n API: PUT /api/v1/workflows/wf-insightly-sync, then retries this execution with the fixed version (loadWorkflow: true)",
      },
      rawPayload: {
        execution: { id: "84213", mode: "trigger", lastNodeExecuted: "Insightly: Update Contact" },
        workflow: { id: "wf-insightly-sync", name: "Insightly → Supabase Contact Sync" },
      },
    },
    {
      id: "evt-002",
      platform: "zapier",
      eventType: "workflow_deactivated",
      status: "new",
      sourceName: "AWM Zapier",
      workflowExternalId: "zap-invoice-sync",
      workflowName: "Xero Invoice → Insightly Opportunity",
      executionExternalId: null,
      executionUrl: ZAP_HISTORY,
      errorMessage:
        "Zap turned off by Zapier: more than 95% of runs errored in the last 7 days (grace period: 24h)",
      errorNode: null,
      errorStack: null,
      occurredAt: ago(95),
      receivedAt: ago(93),
      ingestChannel: "push",
      assignee: null,
      acknowledgedAt: null,
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: false,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: null,
      rawPayload: { trigger: "zap_turned_off", zap: { title: "Xero Invoice → Insightly Opportunity" } },
    },
    {
      id: "evt-003",
      platform: "n8n",
      eventType: "execution_failed",
      status: "new",
      sourceName: "AWM n8n",
      workflowExternalId: "wf-meeting-reminders",
      workflowName: "Meeting Reminder Dispatch",
      executionExternalId: "84188",
      executionUrl: `${N8N_BASE}/workflow/wf-meeting-reminders/executions/84188`,
      errorMessage:
        "Cannot read properties of undefined (reading 'attendee_email') — expression failed in 'Format Reminder'",
      errorNode: "Format Reminder",
      errorStack:
        "ExpressionError: Cannot read properties of undefined (reading 'attendee_email')\n    at Object.evaluate (n8n-workflow/src/Expression.ts:98)",
      occurredAt: ago(47),
      receivedAt: ago(45),
      ingestChannel: "push",
      assignee: null,
      acknowledgedAt: null,
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: true,
      inputPayload: {
        booking: { id: "bk-20418", client: "INS-90233", startsAt: "2026-08-26T09:30:00Z" },
        contact_email: "ops@example-client.co.uk",
      },
      canResubmit: true,
      fixSuggestion: {
        summary: "Guard the attendee-email expression against missing bookings",
        changes: [
          "Change the expression in 'Format Reminder' to {{ $json.booking?.attendee_email ?? $json.contact_email }}",
          "Add an IF node so reminders without any email route to a Slack alert instead of failing the run",
        ],
        mechanism:
          "Applies via n8n API: PUT /api/v1/workflows/wf-meeting-reminders, then retries this execution with the fixed version (loadWorkflow: true)",
      },
      rawPayload: {
        execution: { id: "84188", mode: "trigger", lastNodeExecuted: "Format Reminder" },
        workflow: { id: "wf-meeting-reminders", name: "Meeting Reminder Dispatch" },
      },
    },
    {
      id: "evt-004",
      platform: "n8n",
      eventType: "execution_failed",
      status: "new",
      sourceName: "AWM n8n",
      workflowExternalId: "wf-lead-portal-intake",
      workflowName: "Lead Portal Intake",
      executionExternalId: null,
      executionUrl: null,
      errorMessage: "Trigger failed: webhook registration lost after instance restart",
      errorNode: "Webhook Trigger",
      errorStack: null,
      occurredAt: ago(128),
      receivedAt: ago(126),
      ingestChannel: "push",
      assignee: null,
      acknowledgedAt: null,
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: false,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: {
        summary: "Re-register the lost webhook",
        changes: [
          "Deactivate and reactivate the workflow so n8n re-registers the webhook with the trigger service",
        ],
        mechanism:
          "Applies via n8n API: POST /api/v1/workflows/wf-lead-portal-intake/deactivate, then /activate",
      },
      rawPayload: {
        trigger: {
          error: { name: "TriggerError", context: "webhook registration lost" },
          node: "Webhook Trigger",
        },
        workflow: { id: "wf-lead-portal-intake", name: "Lead Portal Intake" },
      },
    },
    {
      id: "evt-005",
      platform: "zapier",
      eventType: "execution_failed",
      status: "acknowledged",
      sourceName: "AWM Zapier",
      workflowExternalId: "zap-task-booker-outlook",
      workflowName: "Task Booker → Outlook Calendar",
      executionExternalId: "run-77120",
      executionUrl: ZAP_HISTORY,
      errorMessage:
        "Microsoft Outlook returned \"ErrorAccessDenied — access to OData is disabled\" (all Autoreplay attempts exhausted)",
      errorNode: "Create Calendar Event",
      errorStack: null,
      occurredAt: ago(11 * 60 + 30),
      receivedAt: ago(58),
      ingestChannel: "push",
      assignee: "Armand",
      acknowledgedAt: ago(41),
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: false,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: null,
      rawPayload: { trigger: "new_zap_error", zap: { title: "Task Booker → Outlook Calendar" } },
    },
    {
      id: "evt-006",
      platform: "n8n",
      eventType: "execution_failed",
      status: "investigating",
      sourceName: "AWM n8n",
      workflowExternalId: "wf-ml-handovers",
      workflowName: "ML Handover Notifier",
      executionExternalId: "84102",
      executionUrl: `${N8N_BASE}/workflow/wf-ml-handovers/executions/84102`,
      errorMessage: "ECONNREFUSED 10.0.4.12:5432 — Supabase connection pool exhausted",
      errorNode: "Postgres: Insert Handover",
      errorStack:
        "Error: connect ECONNREFUSED 10.0.4.12:5432\n    at TCPConnectWrap.afterConnect (node:net:1300)",
      occurredAt: ago(3 * 60 + 15),
      receivedAt: ago(3 * 60 + 10),
      ingestChannel: "sweep",
      assignee: "Tumisang",
      acknowledgedAt: ago(2 * 60 + 50),
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: true,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: {
        summary: "Use the pooled connection and retry on transient DB errors",
        changes: [
          "Point the Postgres credential at the Supavisor pooler (port 6543) instead of the direct connection",
          "Enable 'Retry On Fail' on 'Postgres: Insert Handover': 3 tries, 5s wait",
        ],
        mechanism:
          "Applies via n8n API: PUT /api/v1/workflows/wf-ml-handovers, then retries this execution with the fixed version (loadWorkflow: true)",
      },
      rawPayload: {
        execution: { id: "84102", mode: "trigger", lastNodeExecuted: "Postgres: Insert Handover" },
        workflow: { id: "wf-ml-handovers", name: "ML Handover Notifier" },
      },
    },
    {
      id: "evt-007",
      platform: "n8n",
      eventType: "execution_failed",
      status: "retried",
      sourceName: "AWM n8n",
      workflowExternalId: "wf-insightly-sync",
      workflowName: "Insightly → Supabase Contact Sync",
      executionExternalId: "83990",
      executionUrl: `${N8N_BASE}/workflow/wf-insightly-sync/executions/83990`,
      errorMessage: "504 Gateway Timeout from Insightly API after 30s",
      errorNode: "Insightly: Get Contacts",
      errorStack: null,
      occurredAt: ago(6 * 60),
      receivedAt: ago(6 * 60),
      ingestChannel: "push",
      assignee: "Tumisang",
      acknowledgedAt: ago(5 * 60 + 40),
      resolvedAt: null,
      retryExecutionId: "84005",
      canRetry: true,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: null,
      rawPayload: {
        execution: { id: "83990", mode: "trigger", lastNodeExecuted: "Insightly: Get Contacts" },
        workflow: { id: "wf-insightly-sync", name: "Insightly → Supabase Contact Sync" },
      },
    },
    {
      id: "evt-008",
      platform: "zapier",
      eventType: "task_halted",
      status: "new",
      sourceName: "AWM Zapier",
      workflowExternalId: "zap-new-lead-insightly",
      workflowName: "New Lead → Insightly",
      executionExternalId: "run-77202",
      executionUrl: ZAP_HISTORY,
      errorMessage: "Task halted: filter condition met no data — \"Lead email exists\" returned empty",
      errorNode: "Filter: Lead email exists",
      errorStack: null,
      occurredAt: ago(9 * 60),
      receivedAt: ago(8 * 60 + 45),
      ingestChannel: "push",
      assignee: null,
      acknowledgedAt: null,
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: false,
      inputPayload: {
        lead: { name: "J. Mokoena", phone: "+27 82 000 0000", email: "", source: "lead-portal" },
      },
      canResubmit: true,
      fixSuggestion: null,
      rawPayload: { trigger: "new_halted_task", zap: { title: "New Lead → Insightly" } },
    },
    {
      id: "evt-009",
      platform: "n8n",
      eventType: "execution_failed",
      status: "resolved",
      sourceName: "AWM n8n",
      workflowExternalId: "wf-daily-ops-digest",
      workflowName: "Daily Ops Digest",
      executionExternalId: "83871",
      executionUrl: `${N8N_BASE}/workflow/wf-daily-ops-digest/executions/83871`,
      errorMessage: "Slack API error: channel_not_found (#ops-digest renamed)",
      errorNode: "Slack: Post Digest",
      errorStack: null,
      occurredAt: ago(26 * 60),
      receivedAt: ago(26 * 60),
      ingestChannel: "push",
      assignee: "Joshua",
      acknowledgedAt: ago(25 * 60),
      resolvedAt: ago(22 * 60),
      retryExecutionId: null,
      canRetry: true,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: null,
      rawPayload: {
        execution: { id: "83871", mode: "trigger", lastNodeExecuted: "Slack: Post Digest" },
        workflow: { id: "wf-daily-ops-digest", name: "Daily Ops Digest" },
      },
    },
    {
      id: "evt-010",
      platform: "zapier",
      eventType: "execution_failed",
      status: "resolved",
      sourceName: "AWM Zapier",
      workflowExternalId: "zap-task-booker-outlook",
      workflowName: "Task Booker → Outlook Calendar",
      executionExternalId: "run-76684",
      executionUrl: ZAP_HISTORY,
      errorMessage: "Required field \"Start time\" is missing from trigger data",
      errorNode: "Create Calendar Event",
      errorStack: null,
      occurredAt: ago(31 * 60),
      receivedAt: ago(20 * 60 + 30),
      ingestChannel: "push",
      assignee: "Armand",
      acknowledgedAt: ago(20 * 60),
      resolvedAt: ago(18 * 60),
      retryExecutionId: null,
      canRetry: false,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: null,
      rawPayload: { trigger: "new_zap_error", zap: { title: "Task Booker → Outlook Calendar" } },
    },
    {
      id: "evt-012",
      platform: "custom_app",
      eventType: "execution_failed",
      status: "new",
      sourceName: "Task Booker Jobs",
      workflowExternalId: "job-reminder-queue-drain",
      workflowName: "Reminder queue drain",
      executionExternalId: "run-2026-08-26-0900",
      executionUrl: null,
      errorMessage: "SMTP relay refused connection: 421 too many concurrent sessions from Graph connector",
      errorNode: "sendReminderBatch",
      errorStack:
        "Error: 421 too many concurrent sessions\n    at GraphMailer.send (apps/jobs/src/mailer.ts:88)\n    at drainReminderQueue (apps/jobs/src/reminders.ts:41)",
      occurredAt: ago(25),
      receivedAt: ago(25),
      ingestChannel: "push",
      assignee: null,
      acknowledgedAt: null,
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: false,
      inputPayload: { batchSize: 40, queuedReminders: 312 },
      canResubmit: false,
      fixSuggestion: null,
      rawPayload: { job: "reminder-queue-drain", host: "taskbooker-worker-1" },
    },
    {
      id: "evt-011",
      platform: "n8n",
      eventType: "execution_failed",
      status: "ignored",
      sourceName: "AWM n8n",
      workflowExternalId: "wf-watchdog",
      workflowName: "Watchdog — attach error workflow",
      executionExternalId: "83704",
      executionUrl: `${N8N_BASE}/workflow/wf-watchdog/executions/83704`,
      errorMessage: "n8n API returned 0 workflows missing an error workflow — nothing to update",
      errorNode: "Stop And Error",
      errorStack: null,
      occurredAt: ago(49 * 60),
      receivedAt: ago(49 * 60),
      ingestChannel: "sweep",
      assignee: null,
      acknowledgedAt: null,
      resolvedAt: null,
      retryExecutionId: null,
      canRetry: true,
      inputPayload: null,
      canResubmit: false,
      fixSuggestion: null,
      rawPayload: {
        execution: { id: "83704", mode: "trigger", lastNodeExecuted: "Stop And Error" },
        workflow: { id: "wf-watchdog", name: "Watchdog — attach error workflow" },
      },
    },
  ];
}
